export { default as Hero } from './Hero.astro'
export { default as Features } from './Features.astro'
export { default as FAQ } from './FAQ.astro'
export { default as CTA } from './CTA.astro'
export { default as Content } from './Content.astro'
export { default as MediaText } from './MediaText.astro'
export { default as LogoGrid } from './LogoGrid.astro'
export { default as ProductFeed } from './ProductFeed.astro'
