import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const rootDir = fileURLToPath(new URL('..', import.meta.url))
const contentDir = path.join(rootDir, 'content')
const seedDir = path.join(rootDir, 'seed')
const seedFile = path.join(seedDir, 'd1-content.sql')

function sqlString(value) {
  return `'${String(value).replace(/'/g, "''")}'`
}

function sqlJson(value) {
  return sqlString(JSON.stringify(value))
}

async function readJson(filePath) {
  return JSON.parse(await fs.readFile(filePath, 'utf-8'))
}

async function main() {
  const site = await readJson(path.join(contentDir, 'site.json'))
  const pageDir = path.join(contentDir, 'pages')
  const pageFiles = (await fs.readdir(pageDir)).filter((entry) => entry.endsWith('.json')).sort()
  const pages = await Promise.all(pageFiles.map((entry) => readJson(path.join(pageDir, entry))))

  const statements = [
    '-- Generated by scripts/generate-d1-seed.mjs',
    'BEGIN TRANSACTION;',
    '',
    [
      'INSERT INTO site_config (site_key, data, updated_at)',
      `VALUES (${sqlString('default')}, ${sqlJson(site)}, ${sqlString(new Date().toISOString())})`,
      'ON CONFLICT(site_key) DO UPDATE SET',
      '  data = excluded.data,',
      '  updated_at = excluded.updated_at;',
    ].join('\n'),
    '',
    ...pages.flatMap((page) => [
      [
        'INSERT INTO pages (id, slug, page_type, data, updated_at)',
        `VALUES (${sqlString(page.id)}, ${sqlString(page.slug)}, ${sqlString(page.pageType)}, ${sqlJson(page)}, ${sqlString(
          new Date().toISOString(),
        )})`,
        'ON CONFLICT(id) DO UPDATE SET',
        '  slug = excluded.slug,',
        '  page_type = excluded.page_type,',
        '  data = excluded.data,',
        '  updated_at = excluded.updated_at;',
      ].join('\n'),
      '',
    ]),
    'COMMIT;',
    '',
  ]

  await fs.mkdir(seedDir, { recursive: true })
  await fs.writeFile(seedFile, statements.join('\n'), 'utf-8')
  console.log(`Generated ${path.relative(rootDir, seedFile)}`)
}

await main()
